In [ ]:
import pandas as pd
df = pd.read_csv('hepatitis.csv')
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live

In [ ]:
df.isna().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

In [ ]:
# Percentage missing values
df.isna().sum()/len(df)*100

age                 0.000000
sex                 0.000000
steroid             0.645161
antivirals          0.000000
fatigue             0.645161
malaise             0.645161
anorexia            0.645161
liver_big           6.451613
liver_firm          7.096774
spleen_palpable     3.225806
spiders             3.225806
ascites             3.225806
varices             3.225806
bilirubin           3.870968
alk_phosphate      18.709677
sgot                2.580645
albumin            10.322581
protime            43.225806
histology           0.000000
class               0.000000
dtype: float64

In [ ]:
# Drop columns with missing values
df.dropna(axis=1)

     age     sex  antivirals  histology class
0     30    male       False      False  live
1     50  female       False      False  live
2     78  female       False      False  live
3     31  female        True      False  live
4     34  female       False      False  live
..   ...     ...         ...        ...   ...
150   46  female       False       True   die
151   44  female       False       True  live
152   61  female       False       True  live
153   53    male       False       True  live
154   43  female       False       True   die

[155 rows x 5 columns]

In [ ]:
# other method - specify column and drop missing rows for that column
copy_df = df
copy_df.dropna(subset=['liver_big'],axis=0,inplace=True)
copy_df.head()

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live

In [ ]:
df.isna().sum()/len(df)*100

age                 0.000000
sex                 0.000000
steroid             0.689655
antivirals          0.000000
fatigue             0.000000
malaise             0.000000
anorexia            0.000000
liver_big           0.000000
liver_firm          0.689655
spleen_palpable     0.689655
spiders             0.689655
ascites             0.689655
varices             0.689655
bilirubin           2.758621
alk_phosphate      16.551724
sgot                1.379310
albumin             8.965517
protime            40.689655
histology           0.000000
class               0.000000
dtype: float64

In [ ]:
# Keep only columns with 80% not null values
df.dropna(thresh=0.8*len(df),axis=1,inplace=True)
list(df)

['age',
 'sex',
 'steroid',
 'antivirals',
 'fatigue',
 'malaise',
 'anorexia',
 'liver_big',
 'liver_firm',
 'spleen_palpable',
 'spiders',
 'ascites',
 'varices',
 'bilirubin',
 'alk_phosphate',
 'sgot',
 'albumin',
 'histology',
 'class']

In [ ]:
# List datatypes
df.dtypes

age                  int64
sex                 object
steroid             object
antivirals            bool
fatigue             object
malaise             object
anorexia            object
liver_big           object
liver_firm          object
spleen_palpable     object
spiders             object
ascites             object
varices             object
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
histology             bool
class               object
dtype: object

In [ ]:
# Select numeric columns
import numpy as np
numeric = df.select_dtypes(include=np.number)
numeric_columns = numeric.columns

In [ ]:
# Fill NaN values in numeric columns with mean value
df[numeric_columns] = df[numeric_columns].fillna(df.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

In [ ]:
df.isna().sum()/len(df)*100

age                0.000000
sex                0.000000
steroid            0.689655
antivirals         0.000000
fatigue            0.000000
malaise            0.000000
anorexia           0.000000
liver_big          0.000000
liver_firm         0.689655
spleen_palpable    0.689655
spiders            0.689655
ascites            0.689655
varices            0.689655
bilirubin          0.000000
alk_phosphate      0.000000
sgot               0.000000
albumin            0.000000
histology          0.000000
class              0.000000
dtype: float64

In [ ]:
# Selecting all object columns, removing the column "class" from them and then converting type of result to bool
boolean_columns = df.select_dtypes(include=np.object).columns.tolist()
boolean_columns.remove('class')
df[boolean_columns] = df[boolean_columns].astype('bool')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
df[boolean_columns].fillna(df.mode())

,sex,steroid,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices
0,True,False,False,False,False,False,False,False,False,False,False
1,True,False,True,False,False,False,False,False,False,False,False
2,True,True,True,False,False,True,False,False,False,False,False
3,True,True,False,False,False,True,False,False,False,False,False
4,True,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
150,True,True,True,True,True,True,False,False,True,True,True
151,True,True,True,False,False,True,True,False,False,False,False
152,True,False,True,True,False,False,True,False,True,False,False
153,True,False,True,False,False,True,False,True,True,False,True
154,True,True,True,False,False,True,False,True,True,True,False

In [ ]:
df.isna().sum()/len(df)*100

age                0.0
sex                0.0
steroid            0.0
antivirals         0.0
fatigue            0.0
malaise            0.0
anorexia           0.0
liver_big          0.0
liver_firm         0.0
spleen_palpable    0.0
spiders            0.0
ascites            0.0
varices            0.0
bilirubin          0.0
alk_phosphate      0.0
sgot               0.0
albumin            0.0
histology          0.0
class              0.0
dtype: float64

In [ ]:
# Using Interpolation to replace missing values
df = pd.read_csv('hepatitis.csv')
df.isna().sum()/len(df)*100

age                 0.000000
sex                 0.000000
steroid             0.645161
antivirals          0.000000
fatigue             0.645161
malaise             0.645161
anorexia            0.645161
liver_big           6.451613
liver_firm          7.096774
spleen_palpable     3.225806
spiders             3.225806
ascites             3.225806
varices             3.225806
bilirubin           3.870968
alk_phosphate      18.709677
sgot                2.580645
albumin            10.322581
protime            43.225806
histology           0.000000
class               0.000000
dtype: float64

In [ ]:
# Selecting only numeric columns
numeric = df.select_dtypes(include=np.number)
numeric_columns = numeric.columns
print(numeric_columns)
df.head(5)

Index(['age', 'bilirubin', 'alk_phosphate', 'sgot', 'albumin', 'protime'], dtype='object')

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live

In [ ]:
# Applying the interpolate() function to numeric columns
df[numeric_columns] = df[numeric_columns].interpolate(method ='linear', limit_direction ='forward')
df.head(5)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,70.5,200.0,4.0,77.5,False,live

In [ ]:
# Getting count, mean, std, min, max, etc.
df.describe()

,age,bilirubin,alk_phosphate,sgot,albumin,protime
count,155.000000,155.000000,155.000000,155.000000,155.000000,152.000000
mean,41.200000,1.436774,105.825806,84.832258,3.822581,60.388158
std,12.565878,1.204578,49.078735,88.728806,0.635119,20.499080
min,7.000000,0.300000,26.000000,14.000000,2.100000,0.000000
25%,32.000000,0.725000,75.000000,32.500000,3.425000,45.875000
50%,39.000000,1.000000,85.000000,55.000000,4.000000,57.000000
75%,50.000000,1.500000,131.500000,99.000000,4.200000,74.000000
max,78.000000,8.000000,295.000000,648.000000,6.400000,100.000000

In [ ]:
# Querying rows where alk_phosphate column has value >= 84
df.query('alk_phosphate >= 84')

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.00,85.0,18.000000,4.000000,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.90,135.0,42.000000,3.500000,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.70,96.0,32.000000,4.000000,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.90,95.0,28.000000,4.000000,75.000000,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,0.95,91.6,34.666667,4.133333,77.000000,False,die
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,20,female,False,False,False,False,False,True,NaN,False,False,False,False,0.90,89.0,152.000000,4.000000,40.000000,True,live
149,36,female,True,False,False,False,False,True,False,False,False,False,False,0.60,120.0,30.000000,4.000000,45.000000,True,live
150,46,female,True,False,True,True,True,True,False,False,True,True,True,7.60,123.0,242.000000,3.300000,50.000000,True,die
151,44,female,True,False,True,False,False,True,True,False,False,False,False,0.90,126.0,142.000000,4.300000,49.333333,True,live
154,43,female,True,False,True,False,False,True,False,True,True,True,False,1.20,100.0,19.000000,3.100000,42.000000,True,die

In [ ]:
# Querying rows where sex is male
df.query('sex == "male"')

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
20,22,male,True,True,True,False,False,True,False,False,False,False,False,0.9,48.0,20.0,4.2,64.0,False,live
24,25,male,False,True,False,False,False,True,False,False,False,False,False,0.4,45.0,18.0,4.3,70.0,False,live
27,58,male,True,False,True,False,False,True,True,False,True,False,False,1.4,175.0,55.0,2.7,36.0,False,live
32,41,male,True,True,True,True,True,True,False,False,False,False,False,0.7,81.0,53.0,5.0,74.0,False,live
33,26,male,False,False,False,False,False,True,True,False,False,False,False,0.5,135.0,29.0,3.8,60.0,False,live
37,20,male,False,False,True,True,True,False,True,True,True,False,False,2.3,150.0,68.0,3.9,95.0,False,live
47,28,male,True,False,True,True,False,True,True,False,False,False,False,1.8,191.0,420.0,3.3,46.0,False,live
59,45,male,False,False,True,True,False,True,False,True,False,False,False,1.0,85.0,75.0,4.4,87.0,False,live
77,34,male,False,True,False,False,False,True,True,False,False,False,False,0.6,30.0,24.0,4.0,76.0,False,live
83,67,male,False,False,True,True,False,True,False,NaN,NaN,NaN,NaN,1.5,179.0,69.0,2.9,79.0,False,live
84,62,male,True,False,True,True,False,True,True,False,True,False,False,1.3,141.0,156.0,3.9,58.0,False,live
90,50,male,False,False,True,False,False,False,True,True,True,False,False,0.9,230.0,117.0,3.4,41.0,True,live
115,69,male,True,False,True,False,False,True,False,False,False,False,False,3.2,119.0,136.0,3.7,51.0,True,live
125,34,male,True,False,True,True,True,False,True,False,True,False,False,0.7,70.0,24.0,4.1,100.0,True,live
153,53,male,False,False,True,False,False,True,False,True,True,False,True,1.5,81.0,19.0,4.1,48.0,True,live

In [ ]:
# Indexing
# 41st element
df.iloc[41]

age                    23
sex                female
steroid              True
antivirals          False
fatigue             False
malaise             False
anorexia            False
liver_big             NaN
liver_firm            NaN
spleen_palpable       NaN
spiders               NaN
ascites               NaN
varices               NaN
bilirubin             4.6
alk_phosphate        56.0
sgot                 16.0
albumin               4.6
protime              40.5
histology           False
class                live
Name: 41, dtype: object

In [ ]:
# Join
if __name__ == '__main__':
    np.random.seed(1)
    left_df = pd.DataFrame({'join_keys': ['a', 'b', 'c', 'd'], 'values':
np.random.randint(10, 99, 4)})
    right_df = pd.DataFrame({'join_keys': ['b', 'd', 'e', 'f'], 'values':
np.random.randint(10, 99, 4)})

    print(left_df)
    print(right_df)

  join_keys  values
0         a      47
1         b      22
2         c      82
3         d      19
  join_keys  values
0         b      85
1         d      15
2         e      89
3         f      74

In [ ]:
left_join = left_df.merge(right=right_df, how='left', on='join_keys')
print(left_join)

  join_keys  values_x  values_y
0         a        47       NaN
1         b        22      85.0
2         c        82       NaN
3         d        19      15.0

In [ ]:
# Aggregate
df = pd.DataFrame(np.random.randn(10, 4),
index = pd.date_range('1/1/2000', periods=10),
columns = ['A', 'B', 'C', 'D'])
print(df)
r = df.rolling(window=3,min_periods=1)
print(r['A'].aggregate(np.sum))

                   A         B         C         D
2000-01-01 -1.105935 -1.654515 -2.363469  1.135345
2000-01-02 -1.017014  0.637362 -0.859907  1.772608
2000-01-03 -1.110363  0.181214  0.564345 -0.566510
2000-01-04  0.729976  0.372994  0.533811 -0.091973
2000-01-05  1.913820  0.330797  1.141943 -1.129595
2000-01-06 -0.850052  0.960820 -0.217418  0.158515
2000-01-07  0.873418 -0.111383 -1.038039 -1.009480
2000-01-08 -1.058257  0.656284 -0.062492 -1.738654
2000-01-09  0.103163 -0.621667  0.275718 -1.090675
2000-01-10 -0.609985  0.306412  1.691826 -0.747954
2000-01-01   -1.105935
2000-01-02   -2.122949
2000-01-03   -3.233312
2000-01-04   -1.397402
2000-01-05    1.533433
2000-01-06    1.793744
2000-01-07    1.937186
2000-01-08   -1.034891
2000-01-09   -0.081675
2000-01-10   -1.565079
Freq: D, Name: A, dtype: float64